In [1]:
import numpy as np

In [2]:
# 1d array
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [3]:
#2d array
b=np.array([(1,2),(3,4)])
b

array([[1, 2],
       [3, 4]])

In [5]:
#3d array
c=np.array([[(1,2),(3,4),(5,6)]])
c

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [7]:
#range array
d=np.arange(1,20,2)
d

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [16]:
#placeholders
a=np.linspace(0,3,5)
print(a)
b=np.zeros((2,2))
print(b)
c=np.ones((2,2))
print(c)
d=np.random.rand((5))
print(d)


[0.   0.75 1.5  2.25 3.  ]
[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
[0.30673968 0.36964997 0.92808385 0.73097299 0.51692564]


In [17]:
#array
a=np.array([(1,2,3),(4,5,6)],dtype=np.int32)
a

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [18]:
a.shape

(2, 3)

In [19]:
len(a)

2

In [21]:
a.ndim

2

In [22]:
a.dtype

dtype('int32')

In [25]:
a=a.astype(np.float32)
print(a.dtype)

float32


In [28]:
#copying and sorting
a=np.array([11,3,6,9,1,2,6,7],dtype=np.float32)
b=np.copy(a)
b

array([11.,  3.,  6.,  9.,  1.,  2.,  6.,  7.], dtype=float32)

In [30]:
a.sort()
a

array([ 1.,  2.,  3.,  6.,  6.,  7.,  9., 11.], dtype=float32)

In [38]:
#array manipulation
a=np.array([11,3,6,9,1,2,6,7,11],dtype=np.float32)
a

array([11.,  3.,  6.,  9.,  1.,  2.,  6.,  7., 11.], dtype=float32)

In [39]:
a=np.append(a,100)
a

array([ 11.,   3.,   6.,   9.,   1.,   2.,   6.,   7.,  11., 100.])

In [43]:
a=np.delete(a,9)
a

array([11.,  3.,  6.,  9.,  1.,  2.,  6.,  7., 11.])

In [47]:
#combining and spliting array
a=np.array([1,2,3],dtype=np.int32)
b=np.array([6,7,8],dtype=np.int32)

c=np.concatenate((a,b))
c

array([1, 2, 3, 6, 7, 8], dtype=int32)

In [48]:
d=np.vstack((a,b))
print(d)
e=np.hstack((a,b))
print(e)

[[1 2 3]
 [6 7 8]]
[1 2 3 6 7 8]


In [51]:
k=np.split(a,3)
k

[array([1], dtype=int32), array([2], dtype=int32), array([3], dtype=int32)]

In [54]:
a=np.array([[1,2],[3,4]])
print(a)
m=a.flatten()       #convert 2d array to 1d
m

[[1 2]
 [3 4]]


array([1, 2, 3, 4])

In [55]:
#transpose
print(a)

b=a.T
print(b)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [56]:
i=np.linalg.inv(a)   #inverse of matrix
i

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [60]:
#operations
a=np.array([1,2,3])
b=np.array([4,6,8])

print(a+b)
print(b-a)
print(a*b)
print(a/b)
print(a**2)
print(np.sqrt(b))
print(np.log(a))
print(np.dot(a,b))

[ 5  8 11]
[3 4 5]
[ 4 12 24]
[0.25       0.33333333 0.375     ]
[1 4 9]
[2.         2.44948974 2.82842712]
[0.         0.69314718 1.09861229]
40


In [63]:
#basic statastics
d=np.mean(a)
print(d)
e=np.median(a)
print(e)
f=np.std(a)
print(f)

2.0
2.0
0.816496580927726


In [67]:
#slicing & indexing
a=np.array([1,3,5,6,3,2,8,6,7])
print(a[2])
print(a[-1])
print(a[0:4])
print(a[::-1])
print(a[1:7:2])

5
7
[1 3 5 6]
[7 6 8 2 3 6 5 3 1]
[3 6 2]


In [69]:
arr=np.empty((8,5))
for i in range(8):
  arr[i]=i

arr

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7.]])

In [70]:
arr[1:5]

array([[1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.]])

In [74]:
arr[[-2,-4,-5]]

array([[6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4.],
       [3., 3., 3., 3., 3.]])

In [75]:
x=np.random.rand(5)
y=np.random.rand(5)

print(x)
print(y)
np.maximum(x,y)

[0.54243331 0.86957014 0.68826806 0.92362344 0.80582123]
[0.37917144 0.93820872 0.43998025 0.62780009 0.91946031]


array([0.54243331, 0.93820872, 0.68826806, 0.92362344, 0.91946031])